server:
  port: 9090
spring:
  application:
    name: iam-service
  datasource:
      url: jdbc:sqlserver://112.196.43.19:1433;databaseName=rbacpoc;integratedSecurity=false;encrypt=false;trustServerCertificate=false
      username: sa
      password: YourPassword123!
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  sql:
    init:
      mode: always
      
logging:
  file:
    path: /opt/aptnx/app/log/
      
springdoc:
  api-docs:
    path: /api-docs
#   http://localhost:8080/swagger-ui/index.html
  swagger-ui:
    enabled: true 